name: Tests
on: 
  pull_request:
    branches: 
      - master
jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          export API_URL="https://swiftenv-api.fuller.li/versions?snapshot=false&platform=ubuntu18.04"
          export SWIFT_VERSION="$(curl -H 'Accept: text/plain' "$API_URL" | tail -n1)"
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - name: Version
        run: |
          export PATH="/home/runner/.swiftenv/bin:/home/runner/.swiftenv/shims:$PATH"
          swift --version
      - name: Build
        run: |
          export PATH="/home/runner/.swiftenv/bin:/home/runner/.swiftenv/shims:$PATH"
          swift build
      - name: Test
        run: |
          export PATH="/home/runner/.swiftenv/bin:/home/runner/.swiftenv/shims:$PATH"
          swift test --enable-test-discovery
