name: Tests
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  macOS:
    name: Swift on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test
  linux:
    name: Swift on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: fwal/setup-swift@master
      - uses: actions/checkout@v2
      - name: Version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test
