name: Tests
on: 
  pull_request:
    branches: 
      - master
jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: [5.1.4]
      fail-fast: false
    name: Swift ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env: 
      SWIFT_VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - name: Version
        run: |
          export PATH="/home/runner/.swiftenv/bin:/home/runner/.swiftenv/shims:$PATH"
          swift --version
      - name: Build
        run: |
          export PATH="/home/runner/.swiftenv/bin:/home/runner/.swiftenv/shims:$PATH"
          swift build
      - name: Test
        run: |
          export PATH="/home/runner/.swiftenv/bin:/home/runner/.swiftenv/shims:$PATH"
          swift test --enable-test-discovery
